[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
thiserror = "2"
serde = { version = "1" }
serde_json = "1"
util = { path = "../util" }
eframe = { version = "0.33" }
egui = { version = "0.33", features = ["serde"] }
egui_extras = { version = "0.33.3", features = ["image"] }

[features]
# Disables the console that automatically opens when you run an executable on
# Windows.
no-console = []
