[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11.8"
log = "0.4"
wgpu = "27.0.0"
pollster = "0.4"
util = { version = "0.1.0", path = "../util" }
media = { version = "0.1.0", path = "../media" }